app/urls.py
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import path
from text_flow import settings
from .views import HomePage, Login, Logout, SignIn, RoomView, CreateRoomView
from app import views

app_name = 'app'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('create_room/', login_required(CreateRoomView.as_view()), name='create_room'),
    path('ajax/send_circle/', views.send_circle, name='send_circle'),
    path('ajax/delete_room/', views.delete_room, name='delete_room'),
    path('ajax/stop_drawing/', views.stop_drawing, name='stop_drawing'),
    path('ajax/circle_list/', views.circle_list, name='circle_list'),
    path('room/<int:room_id>/', login_required(RoomView.as_view()), name='room'),
    path('room/download/<int:room_id>/', views.download_image, name='download_image'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', login_required(Logout.as_view()), name='logout'),
    path('signin/', SignIn.as_view(), name='signin'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

text_flow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.contrib.auth.models import User
from django.db import models


class Room(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    users = models.ManyToManyField(User, through='RoomToUser', through_fields=('room', 'user'))
    image = models.ImageField(upload_to='images', blank=True, null=True)
    is_open = models.BooleanField(default=True)
    is_drawing = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    num_of_circles = models.IntegerField(default=0)
    text = models.TextField(default='Hello World')


class RoomToUser(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, models.CASCADE)
    room = models.ForeignKey(Room, models.CASCADE)
    is_host = models.BooleanField()


class Circle(models.Model):
    id = models.AutoField(primary_key=True)
    x = models.IntegerField()
    y = models.IntegerField()
    r = models.IntegerField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    index = models.IntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.index is None:
            self.room.num_of_circles += 1
            self.index = self.room.num_of_circles
            self.room.save()
        return super().save(*args, **kwargs)

app/forms.py
from django import forms


class RoomForm(forms.Form):
    name = forms.CharField(label='name')
    text = forms.CharField(label='text')

app/views.py
import os
import string
from random import choices
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.core.files import File
from django.http import HttpResponseRedirect, JsonResponse, FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, FormView
from app.forms import RoomForm
from app.models import Room, RoomToUser, Circle
from app.image_text_wrap.wrap import get_image


def send_circle(request):
    """
    Создает круг, полученный из ajax запроса
    """
    if request.is_ajax() and request.method == 'POST':
        circle = Circle(
            x=request.POST.get('x'),
            y=request.POST.get('y'),
            r=request.POST.get('r'),
            room_id=request.POST.get('room_id')
        )
        circle.save()
        return JsonResponse({'status': 'Success'})


def delete_room(request):
    """
    Удаляет закрывает комнату по ajax запросу
    """
    if request.is_ajax() and request.method == 'POST':
        room = Room.objects.get(id=request.POST.get('room_id'))
        room.is_open = False
        room.save()
        return JsonResponse({'status': 'Success'})


def stop_drawing(request):
    """
    останавливает комнату и генерирует изображение
    """
    if request.is_ajax() and request.method == 'POST':
        room = Room.objects.get(id=request.POST.get('room_id'))
        room.is_drawing = False
        # получаем список кругов в необходимом для входа формате
        circles = room.circle_set.all()
        circle_list = [(circle.x, circle.y, circle.r) for circle in circles]
        # получаем изображение в формате PIL
        image = get_image(circle_list, room.text)
        # сохраняем в файл и загружаем в бд
        temp_name = room.name
        temp_name += str(choices(string.ascii_lowercase, k=5))
        temp_name += '.png'
        image.save(temp_name, format='PNG')
        room.image.save(room.name + '.png', File(open(temp_name, 'rb')))
        room.save()
        os.remove(temp_name)
        return JsonResponse({'status': 'Success'})


@login_required
def download_image(request, room_id):
    """
    возвращает картинку
    """
    room = Room.objects.get(id=room_id)
    return FileResponse(open(room.image.path, 'rb'))


def circle_list(request):
    """
    возвращает текущий список кругов по комнате
    """
    if request.is_ajax() and request.method == 'GET':
        return render(request, 'ajax\\circle_list.html', {'circles': Room.objects.get(id=request.GET.get('room_id')).circle_set.all().order_by('index')})


class HomePage(ListView):
    """
    Домашняя страница со списком комнат
    """
    template_name = 'html/index.html'
    context_object_name = 'rooms'
    queryset = Room.objects.filter(is_open=True).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = RoomForm
        return context


class CreateRoomView(FormView):
    """
    Класс для создания комнаты
    """
    form_class = RoomForm

    def form_valid(self, form):
        room = Room(name=form.cleaned_data['name'], text=form.cleaned_data['text'])
        room.save()
        room.users.add(self.request.user, through_defaults={'is_host': True})
        self.kwargs['room_id'] = room.id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('app:room', args=[self.kwargs['room_id']])


class RoomView(DetailView):
    """
    Просмотр комнаты
    """
    model = Room
    template_name = 'html/room.html'
    context_object_name = 'room'
    pk_url_kwarg = 'room_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['host'] = get_object_or_404(RoomToUser, room=context['room'], is_host=True).user
        context['circles'] = context['room'].circle_set.all().order_by('index')
        context['users'] = context['room'].users.all()
        return context

    def get(self, request, *args, **kwargs):
        room = Room.objects.get(id=kwargs['room_id'])
        # если нет доступа в комнату, то переадресация на домашнюю
        if room.is_open is False or (room.is_drawing is False and request.user not in room.users.all()):
            return redirect('app:home')
        else:
            if request.user not in room.users.all():
                room.users.add(request.user, through_defaults={'is_host': False})
            return super().get(request, *args, *kwargs)


class Login(LoginView):
    template_name = 'html/login.html'
    authentication_form = AuthenticationForm


class Logout(LogoutView):
    pass


class SignIn(CreateView):
    form_class = UserCreationForm
    template_name = 'html/signin.html'
    success_url = reverse_lazy('app:home')

    def form_valid(self, form):
        form.save()
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
        login(self.request, user)
        return HttpResponseRedirect(self.success_url)

templates/ajax/circle_list.html
{#Фрагмент для обновления списка ajax#}
<div class="col-lg-5 col-md-7">
    <ul class="list-group mx-1">
        {% for circle in circles %}
            <li class="mb-1 list-group-item">#{{ circle.index }} x: {{ circle.x }}, y: {{ circle.y }},
                R: {{ circle.r }}</li>

        {% endfor %}
    </ul>
</div>

templates/base.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>{% block title %}Обертка текста{% endblock %} | iCal Network</title>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'app:home' %}">Обертка текста</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if 'home' in request.resolver_match.view_name %}active{% endif %}">
                <a class="nav-link" href="{% url 'app:home' %}">Главная</a>
            </li>


        </ul>
        {% if not user.is_authenticated %}
            <a class="btn btn-primary ml-2" href="{% url 'app:login' %}">Вход</a>{% else %}
            <a class="btn btn-primary ml-2" href="{% url 'app:logout' %}">Выход</a>{% endif %}
    </div>
</nav>

{% block content %}{% endblock %}

<footer class="container">
    <hr>
    <p>&copy; iCal Network 2020-2021</p>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

{% block javascript %}{% endblock %}
</body>

</html>

templates/html/index.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
    <main role="main">
        {% if user.is_authenticated %}
            <div class="container">
                <div class="row">
                    {#                Кнопка для вызова формы#}
                    <div class="col-lg-1">
                        <button class="badge bg-primary mb-1" id="modal-button" data-bs-toggle="modal"
                                data-bs-target="#modal">Создать
                        </button>
                    </div>
                    <div class="col-lg-8 col-md-11 col-sm-12">
                        <div class="row">
                            <div class="list-group col-lg-9 col-md-10 col-sm-11 col-12 mx-auto">
                                {#Список комнат#}
                                {% for room in rooms %}
                                    <a href="{% url 'app:room' room.id %}"
                                       class="list-group-item list-group-item-action flex-column align-items-start {% if room.is_drawing %}active{% endif %}">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="mb-1">{{ room.name }}</h5>
                                            <small>Статус: {% if room.is_drawing %}активна{% else %}
                                                остановлена{% endif %}</small>
                                        </div>
                                        <p class="mb-1">Текст: {{ room.text|truncatechars:190 }}
                                        </p>
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col"></div>
                </div>
            </div>
            {#            Всплывающая форма#}
            <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Создать комнату</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form method="post" action="{% url 'app:create_room' %}">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label>Название</label>
                                    {% render_field form.name class+="form-control" %}
                                    <small class="form-text text-muted">Название комнаты</small>
                                </div>
                                <div class="form-group">
                                    <label>Текст</label>
                                    {% render_field form.text class+="form-control" %}
                                    <small class="form-text text-muted">Текст картинки</small>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                <button type="submit" class="btn btn-primary">Создать</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endif %}


    </main>
{% endblock %}

{% block javascript %}
    {#    Код для работы всплывающей формы#}
    <script>
        var myModal = document.getElementById('myModal')
        var myInput = document.getElementById('myInput')

        myModal.addEventListener('shown.bs.modal', function () {
            myInput.focus()
        })
    </script>
{% endblock %}

templates/html/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <main role="main">
        <div class="container">
            <form class="form-group w-50 my-3" method="post" action="{% url 'app:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    {% if form.errors %}<small class="form-text text-primary">Неудача</small>{% endif %}
                    <label>Логин</label>
                    {% render_field form.username class+="form-control" %}
                    <small class="form-text text-muted">Имя пользователя</small>
                </div>
                <div class="form-group">
                    <label>Пароль</label>
                    {% render_field form.password class+="form-control" %}
                </div>
                <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                <p>Нет аккаунта? <a href="{% url 'app:signin' %}">Регистрация</a></p>
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    </main>
{% endblock %}

templates/html/room.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Комната {{ room.name }}{% endblock %}

{% block content %}
    <main role="main">
        Название: {{ room.name }}
        Текст: {{ room.text }}<br>
        Координаты x: [0;600], y: [0:900]<br>
{#    Форма добавления круга#}
        <form class="form-group w-50 my-3" method="post">
            <div class="input-group mb-3">
                <span class="input-group-text">x</span>
                <input type="text" class="form-control" placeholder="x coord" required name="x">
                <span class="input-group-text">y</span>
                <input type="text" class="form-control" placeholder="y coord" required name="y">
                <span class="input-group-text">R</span>
                <input type="text" class="form-control" placeholder="radius" required name="r">
                <button type="submit" class="btn btn-primary" id="addButton">Добавить</button>
                <button type="button" class="btn btn-primary" id="updateButton">Обновить</button>
                <input type="hidden" value="{{ room.id }}" name="room_id" id="roomID">
            </div>
        </form>
{#        Кнопки создателя комнаты - Остановить и Удалить#}
        {% if user == host %}
            {% if room.is_drawing %}
                <button type="submit" class="btn btn-primary" id="stopDrawing">Остановить рисование</button>{% endif %}
            <button type="submit" class="btn btn-primary" id="deleteRoom">Удалить комнату</button>
        {% endif %}
{#        Изображение и скачать изображение#}
        {% if user in users and room.is_drawing == False and room.image %}
            <br>
            <img src="{{ room.image.url }}">
            <br>
            <a href="{% url 'app:download_image' room.id %}" class="btn btn-primary" download>Скачать</a>
        {% endif %}

        {# Список кругов #}
        <div class="container mt-3">
            <div class="row" id="circleList">
                <div class="col-lg-5 col-md-7">
                    <ul class="list-group mx-1">
                        {% for circle in circles %}
                            <li class="mb-1 list-group-item">#{{ circle.index }} x: {{ circle.x }}, y: {{ circle.y }},
                                R: {{ circle.r }}</li>

                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </main>
{% endblock %}
{% block javascript %}
    <script>
        //функция для получения кука
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        // хэндлер который обновляет список кругов
        const updateList = function (event) {
            $.get(
                "{% url 'app:circle_list' %}",
                {room_id: $('#roomID').val()},
                "html"
            ).done((data, textStatus, jqXHR) => {
                $('#circleList').html(data)
            }).fail((jqXHR, textStatus, error) => {
                alert(`Error: ${textStatus} ${error}`)
            });

        }

        $(document).ready(() => {
            $.ajaxSetup({
                headers: {"X-CSRFToken": getCookie("csrftoken")}
            });
            // хэндлер для добавления круга
            $('#addButton').on("click", function (event) {
                if ($("input[required]").val().length !== 0) {
                    event.preventDefault();
                    const button = $(this);
                    $.ajax({
                        url: "{% url 'app:send_circle' %}",
                        data: button.parents("form").serialize(),
                        type: "POST",
                        dataType: "json"
                    }).done((data, textStatus, jqXHR) => {
                        if (data.status === 'Success') {
                            updateList(event);
                        } else
                            alert('Error');
                    }).fail((jqXHR, textStatus, error) => {
                        alert(`Error: ${textStatus} ${error}`)
                    });
                }
            })
            // хэндлер для обновления списка
            $('#updateButton').on("click", updateList);
            // хэндлер для удаления комнаты
            $('#deleteRoom').on("click", function (event) {
                event.preventDefault();
                $.ajax({
                    url: "{% url 'app:delete_room' %}",
                    data: {room_id: $('#roomID').val()},
                    type: "POST",
                    dataType: "json"
                }).done((data, textStatus, jqXHR) => {
                    if (data.status === 'Success') {
                        window.location.href = "{% url 'app:home' %}";
                    } else
                        alert('Error');
                }).fail((jqXHR, textStatus, error) => {
                    alert(`Error: ${textStatus} ${error}`)
                });
            });
            // хэндлер для остановки комнаты
            $('#stopDrawing').on("click", function (event) {
                event.preventDefault();
                $.ajax({
                    url: "{% url 'app:stop_drawing' %}",
                    data: {room_id: $('#roomID').val()},
                    type: "POST",
                    dataType: "json"
                }).done((data, textStatus, jqXHR) => {
                    if (data.status === 'Success') {
                        location.reload();
                    } else
                        alert('Error');
                }).fail((jqXHR, textStatus, error) => {
                    alert(`Error: ${textStatus} ${error}`)
                });
            });

        })
    </script>
{% endblock %}

templates/html/signin.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    {% load widget_tweaks %}
    <main role="main">
        <div class="container">
            <form class="form-group w-50 my-3" method="post" action="{% url 'app:signin' %}">
                {% csrf_token %}
                <div class="form-group">
                    {% if form.errors %}<small class="form-text text-primary">Неудача</small>{% endif %}
                    <label>Логин</label>
                    {% render_field form.username class+="form-control" %}
                    <small class="form-text text-muted">Имя пользователя</small>
                </div>
                <div class="form-group">
                    <label>Пароль</label>
                    {% render_field form.password1 class+="form-control" %}
                </div>
                <div class="form-group">
                    <label>Повторите пароль</label>
                    {% render_field form.password2 class+="form-control" %}
                </div>
                <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                <button type="submit" class="btn btn-primary">Регистрация</button>
            </form>
        </div>
    </main>
{% endblock %}